CREATE TABLE IF NOT EXISTS user_companies (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                                email VARCHAR(255) NOT NULL UNIQUE ,
                                name VARCHAR(255),
                                password VARCHAR(255)

);
