CREATE TABLE  IF NOT EXISTS orders (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        additional_requirements VARCHAR(255),
                        closed_date TIMESTAMP(6),
                        created_date TIMESTAMP(6) NOT NULL,
                        delivery_address VARCHAR(255),
                        download_address VARCHAR(255),
                        height VARCHAR(255),
                        length VARCHAR(255),
                        name VARCHAR(255),
                        weight VARCHAR(255),
                        width VARCHAR(255),
                        user_id BIGINT NOT NULL REFERENCES users(id)
);

