CREATE TABLE IF NOT EXISTS carrier_companies (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   name VARCHAR(255),
                                   user_company_id BIGINT NOT NULL REFERENCES user_companies(id)
);
