CREATE TABLE IF NOT EXISTS carrier_representative (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                                        additionally VARCHAR(255),
                                        email VARCHAR(255),
                                        carrier_company_id BIGINT NOT NULL REFERENCES carrier_companies(id)

);


