CREATE TABLE IF NOT EXISTS invites (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         created_at TIMESTAMP(6),
                         token VARCHAR(255) unique ,
                         user_company_id BIGINT NOT NULL REFERENCES user_companies(id)
);

