spring:

  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  profiles:
    active: dev
  output:
    ansi:
      enabled: ALWAYS


logging:
  config: classpath:logback.xml

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus, actuator
  prometheus:
    metrics:
      export:
        enabled: true


  metrics:
    tags:
      application: ${spring.application.name}
app:
  upload-dir: ./uploads