spring:
  application:
    name: MailMancer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: service_user_application
    password: service_user_password
  liquibase:
    url: ${spring.datasource.url}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

