spring:
  application:
    name: MailMancer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres

    password: service_user_password
  jpa:
    hibernate:
      ddl-auto: none
server:
  address: 0.0.0.0