spring:
  application:
    name: MailMancerDemo
  liquibase:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: myuser
    password: mypassword
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
