spring:
  application:
    name: MailMancer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: service_user_application
    password: service_user_password
  jpa:
    hibernate:
      ddl-auto: none
