on:
  pull_request:
    branches:
      - main
  push:

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Execute Gradle build
        run: cd backend && ./gradlew build

      - name: Execute Gradle test
        run: cd backend && ./gradlew test

      - name: Execute Gradle check
        run: cd backend && ./gradlew check