name: CI Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build backend with Gradle
        run: cd backend && ./gradlew build --no-daemon

      - name: Run backend tests
        run: cd backend && ./gradlew test --no-daemon

      - name: Start Docker Compose stack
        run: docker compose -f docker-compose.yml up --build -d

      - name: Show running containers
        run: docker ps

      - name: Show container logs
        run: docker compose logs
